export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const FETCH_COURSES = 'FETCH_COURSES';
export const ADD_COURSE = 'ADD_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';

export const FETCH_MOCKTESTS = 'FETCH_MOCKTESTS';
export const ADD_MOCKTEST = 'ADD_MOCKTEST';
export const UPDATE_MOCKTEST = 'UPDATE_MOCKTEST';
export const DELETE_MOCKTEST = 'DELETE_MOCKTEST';
